spring:
  application:
    name: java-21-springboot-template
  
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preferQueryMode=simple
    username: postgres.fcwwtnfyhiibrnbldmfw
    password: HoiRens-12345
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

supabase:
  url: ${SUPABASE_URL:https://fcwwtnfyhiibrnbldmfw.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:your-anon-key-here}

server:
  port: 8080

